name: CI
on: 
  push:
    branches:
      - master

jobs: 
  flutter-test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
  
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [flutter-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build-android:
    name: Build Android AppBundle
    runs-on: ubuntu-latest
    needs: [flutter-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: 12
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle


